### ISSUE TITLE
Difference with DoubleEndedIterator?

### ISSUE THREAD

**Issue by llebout** [sbillig/bidir_iter#1]
Hello,

What is the fundamental difference between this and the [DoubleEndedIterator](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html) trait?

Thanks

**Comment by sbillig** [comment]
DoubleEndedIterator is effectively two iterators; one that's moving forward from the start of the collection, and one that's moving backward from the end. A bidirectional iterator is more like a cursor. You start in one position, and can move the single cursor forward and backward.

I wrote this for walking forward and backward through a flume log, which isn't very compelling beyond viewing the messages in the log to, say, better understand the structure of messages. I'm not terribly fond of the flume offset log as a data store, so none of this is particularly interesting to me at the moment, FWIW.

**Comment by llebout** [comment]
Okay, I see, Thanks.
